




.build/uno/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/sketch.ino[0m
	@/home/marvin/workspace/checkin-nfc-toledos-palace/env/bin/ino preproc  -o $@ $^


all : .build/uno/src/sketch.cpp
	@true

