























.build/uno/PN532_SPI/PN532_SPI.o : lib/PN532_SPI/PN532_SPI.cpp
	@echo [93mPN532_SPI/PN532_SPI.cpp[0m
	@mkdir -p .build/uno/PN532_SPI
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PN532_SPI/PN532_SPI.cpp
include .build/uno/PN532_SPI/PN532_SPI.d



.build/uno/PN532_SPI/libPN532_SPI.a : .build/uno/PN532_SPI/PN532_SPI.o
	@echo [92mLinking libPN532_SPI.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/uno/NDEF/NdefRecord.o : lib/NDEF/NdefRecord.cpp
	@echo [93mNDEF/NdefRecord.cpp[0m
	@mkdir -p .build/uno/NDEF
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/NDEF/NdefRecord.cpp
include .build/uno/NDEF/NdefRecord.d

.build/uno/NDEF/NfcTag.o : lib/NDEF/NfcTag.cpp
	@echo [93mNDEF/NfcTag.cpp[0m
	@mkdir -p .build/uno/NDEF
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/NDEF/NfcTag.cpp
include .build/uno/NDEF/NfcTag.d

.build/uno/NDEF/NfcAdapter.o : lib/NDEF/NfcAdapter.cpp
	@echo [93mNDEF/NfcAdapter.cpp[0m
	@mkdir -p .build/uno/NDEF
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/NDEF/NfcAdapter.cpp
include .build/uno/NDEF/NfcAdapter.d

.build/uno/NDEF/Ndef.o : lib/NDEF/Ndef.cpp
	@echo [93mNDEF/Ndef.cpp[0m
	@mkdir -p .build/uno/NDEF
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/NDEF/Ndef.cpp
include .build/uno/NDEF/Ndef.d

.build/uno/NDEF/MifareUltralight.o : lib/NDEF/MifareUltralight.cpp
	@echo [93mNDEF/MifareUltralight.cpp[0m
	@mkdir -p .build/uno/NDEF
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/NDEF/MifareUltralight.cpp
include .build/uno/NDEF/MifareUltralight.d

.build/uno/NDEF/MifareClassic.o : lib/NDEF/MifareClassic.cpp
	@echo [93mNDEF/MifareClassic.cpp[0m
	@mkdir -p .build/uno/NDEF
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/NDEF/MifareClassic.cpp
include .build/uno/NDEF/MifareClassic.d

.build/uno/NDEF/NdefMessage.o : lib/NDEF/NdefMessage.cpp
	@echo [93mNDEF/NdefMessage.cpp[0m
	@mkdir -p .build/uno/NDEF
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/NDEF/NdefMessage.cpp
include .build/uno/NDEF/NdefMessage.d



.build/uno/NDEF/libNDEF.a : .build/uno/NDEF/NdefRecord.o .build/uno/NDEF/NfcTag.o .build/uno/NDEF/NfcAdapter.o .build/uno/NDEF/Ndef.o .build/uno/NDEF/MifareUltralight.o .build/uno/NDEF/MifareClassic.o .build/uno/NDEF/NdefMessage.o
	@echo [92mLinking libNDEF.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/uno/SPI/SPI.o : /usr/share/arduino/libraries/SPI/SPI.cpp
	@echo [93mSPI/SPI.cpp[0m
	@mkdir -p .build/uno/SPI
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/SPI/SPI.cpp
include .build/uno/SPI/SPI.d



.build/uno/SPI/libSPI.a : .build/uno/SPI/SPI.o
	@echo [92mLinking libSPI.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/uno/PN532/emulatetag.o : lib/PN532/emulatetag.cpp
	@echo [93mPN532/emulatetag.cpp[0m
	@mkdir -p .build/uno/PN532
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PN532/emulatetag.cpp
include .build/uno/PN532/emulatetag.d

.build/uno/PN532/mac_link.o : lib/PN532/mac_link.cpp
	@echo [93mPN532/mac_link.cpp[0m
	@mkdir -p .build/uno/PN532
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PN532/mac_link.cpp
include .build/uno/PN532/mac_link.d

.build/uno/PN532/llcp.o : lib/PN532/llcp.cpp
	@echo [93mPN532/llcp.cpp[0m
	@mkdir -p .build/uno/PN532
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PN532/llcp.cpp
include .build/uno/PN532/llcp.d

.build/uno/PN532/snep.o : lib/PN532/snep.cpp
	@echo [93mPN532/snep.cpp[0m
	@mkdir -p .build/uno/PN532
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PN532/snep.cpp
include .build/uno/PN532/snep.d

.build/uno/PN532/PN532.o : lib/PN532/PN532.cpp
	@echo [93mPN532/PN532.cpp[0m
	@mkdir -p .build/uno/PN532
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PN532/PN532.cpp
include .build/uno/PN532/PN532.d



.build/uno/PN532/libPN532.a : .build/uno/PN532/emulatetag.o .build/uno/PN532/mac_link.o .build/uno/PN532/llcp.o .build/uno/PN532/snep.o .build/uno/PN532/PN532.o
	@echo [92mLinking libPN532.a[0m
	@/usr/bin/avr-ar rcs $@ $^







.build/uno/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/uno/arduino/wiring_digital.d

.build/uno/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/uno/arduino/wiring.d

.build/uno/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/uno/arduino/wiring_shift.d

.build/uno/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/uno/arduino/WInterrupts.d

.build/uno/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/uno/arduino/wiring_pulse.d

.build/uno/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/uno/arduino/wiring_analog.d






.build/uno/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/uno/arduino/HardwareSerial.d

.build/uno/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/uno/arduino/HID.d

.build/uno/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/uno/arduino/Print.d

.build/uno/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/uno/arduino/new.d

.build/uno/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/uno/arduino/CDC.d

.build/uno/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/uno/arduino/IPAddress.d

.build/uno/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/uno/arduino/WString.d

.build/uno/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/uno/arduino/Stream.d

.build/uno/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/uno/arduino/main.d

.build/uno/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/uno/arduino/WMath.d

.build/uno/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/uno/arduino/USBCore.d

.build/uno/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/uno/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/uno/arduino/Tone.d



.build/uno/arduino/libarduino.a : .build/uno/arduino/wiring_digital.o .build/uno/arduino/wiring.o .build/uno/arduino/wiring_shift.o .build/uno/arduino/WInterrupts.o .build/uno/arduino/wiring_pulse.o .build/uno/arduino/wiring_analog.o .build/uno/arduino/HardwareSerial.o .build/uno/arduino/HID.o .build/uno/arduino/Print.o .build/uno/arduino/new.o .build/uno/arduino/CDC.o .build/uno/arduino/IPAddress.o .build/uno/arduino/WString.o .build/uno/arduino/Stream.o .build/uno/arduino/main.o .build/uno/arduino/WMath.o .build/uno/arduino/USBCore.o .build/uno/arduino/Tone.o
	@echo [92mLinking libarduino.a[0m
	@/usr/bin/avr-ar rcs $@ $^















.build/uno/src/sketch.o : .build/uno/src/sketch.cpp
	@echo [93msrc/sketch.cpp[0m
	@mkdir -p .build/uno/src
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/PN532_SPI -Ilib/NDEF -Ilib/NDEF/tests -Ilib/NDEF/tests/NfcTagTest -Ilib/NDEF/tests/NdefUnitTest -Ilib/NDEF/tests/NdefMemoryTest -Ilib/NDEF/tests/NdefMessageTest -I/usr/share/arduino/libraries/SPI -Ilib/PN532 -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/uno/src/sketch.cpp
include .build/uno/src/sketch.d







.build/uno/firmware.elf : .build/uno/src/sketch.o .build/uno/PN532_SPI/libPN532_SPI.a .build/uno/NDEF/libNDEF.a .build/uno/SPI/libSPI.a .build/uno/PN532/libPN532.a .build/uno/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/uno/firmware.hex : .build/uno/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/uno/src/dependencies.d .build/uno/arduino/dependencies.d .build/uno/PN532_SPI/dependencies.d .build/uno/NDEF/dependencies.d .build/uno/SPI/dependencies.d .build/uno/PN532/dependencies.d

all : .build/uno/firmware.hex
	@true

